# Source: cluster-api-byoh/templates/byoh-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: b9415f89-control-plane
  namespace: b9415f89
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: control-plane
