# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: b9415f89-md-normal
  namespace: b9415f89
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: worker
